# -*- coding: utf-8 -*-
"""#2 Detect a voice command

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x-g1i5JUZJgU1ANSP-1eLJKmjt9XUknc?usp=sharing

# **Detect a voice command**

"""

from IPython.display import Audio
import matplotlib.pyplot as plt
from fastdtw import fastdtw
import librosa

# Load audio (The Beatles)
y, sr = librosa.load('/content/The Beatles - This Boy.mp3')
plt.figure(figsize=(15,4))
plt.plot(y[2000000:2001000])
plt.show()

# Load a phrase
phrase, sr_phrase = librosa.load('/content/Phrase.m4a')
plt.figure(figsize=(15,4))
plt.plot(phrase)
plt.show()

# Listen to the phrase
Audio(data=phrase, rate=sr_phrase)

# Load a word
word, sr_word = librosa.load('/content/Word.m4a')
word = word[17500:36000]
plt.figure(figsize=(15,4))
plt.plot(word)
plt.show()

# Listen to the word
Audio(data=word, rate=sr_word)

# Look for the command
word_len = word.shape[0]
matches = []
step = 100
for i in range(0, phrase.shape[0]-word_len, step):
  cutout = phrase[i:i+word_len]
  matches.append([fastdtw(word, cutout)[0], i])
match_i = sorted(matches)[0][1]

# Carve match out and play
match = phrase[match_i:match_i+word_len]
Audio(data=match, rate=sr_word)

# Waves match
plt.figure(figsize=(15,4))
plt.plot(word[7500:10000])
plt.plot(match[7500:10000])
plt.show()
