# -*- coding: utf-8 -*-
"""#12 Find and replace in image

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19vlRbI_bam7cV4HLOtz70kZaLSlf5rAR?usp=sharing

# **Find and replace in image**


"""

import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
import cv2

# Load a picture
picture = np.array(Image.open('/content/picture.png').convert('RGBA'))
plt.imshow(picture)

# Load a penguin
penguin = np.array(Image.open('/content/penguin.png').convert('RGBA'))
plt.imshow(penguin)

# Find a penguin
image = cv2.cvtColor(picture, cv2.COLOR_RGBA2GRAY)
templ = cv2.cvtColor(penguin, cv2.COLOR_RGBA2GRAY)

heat_map = cv2.matchTemplate(image, templ, cv2.TM_CCOEFF_NORMED)

w, h = templ.shape
y, x = np.unravel_index(np.argmax(heat_map), heat_map.shape)
cv2.rectangle(picture, (x,y), (x+w, y+h), (255,0,0,255), 5)

plt.imshow(picture)

# Load a pink penguin
pink = np.array(Image.open('/content/pink.png').convert('RGBA'))
plt.imshow(pink)

# Replace black with pink
picture = np.array(Image.open('/content/picture.png').convert('RGBA'))

pink[:,:,3][pink[:,:,1]==255]=0
picture[y:y+h,x:x+w][pink[:,:,1]!=255]=0
picture[y:y+h,x:x+w] = picture[y:y+h,x:x+w] + pink

plt.imshow(picture)

# What if resized and rotated?
picture = np.array(Image.open('/content/picture1.png').convert('RGBA'))

image = cv2.cvtColor(picture, cv2.COLOR_RGBA2GRAY)
templ = cv2.cvtColor(penguin, cv2.COLOR_RGBA2GRAY)

heat_map = cv2.matchTemplate(image, templ, cv2.TM_CCOEFF_NORMED)

w, h = templ.shape
y, x = np.unravel_index(np.argmax(heat_map), heat_map.shape)
cv2.rectangle(picture, (x,y), (x+w, y+h), (255,0,0,255), 5)

plt.imshow(picture)
