# -*- coding: utf-8 -*-
"""#8 Count stars in the sky

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16TjpZukL_Wztg1IUbxuy6kytIxPRx2lf?usp=sharing

# **Count stars in the sky**


"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
import cv2

# Load a photo
stars = np.array(Image.open('/content/stars.png').convert('RGB')).astype('uint8')
size = stars.shape

# Separate stars from the sky
stars = stars.reshape(-1, 3)
kmean = KMeans(n_clusters=2)
kmean.fit(stars)
clusters = kmean.labels_

# Show the binary picture
clustered_stars = clusters.reshape(size[0],size[1]).astype('uint8')
plt.figure(figsize=(15,10))
plt.imshow(clustered_stars, cmap='gray')
plt.axis('off')
plt.show()

# Count stars
print('There are %.u stars in this sky' % cv2.connectedComponents(clustered_stars)[0])
