# -*- coding: utf-8 -*-
"""#20 Using microphone in Colab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vgaP_1SUppsQtkywFSN2Qey8nvzDohQc?usp=sharing

# **Using microphone in Colab**

"""

from IPython.display import HTML, Javascript
from google.colab.output import eval_js
import base64

js = Javascript("""

  async function recordAudio() {

    const div = document.createElement('div');
    const audio = document.createElement('audio');
    const strtButton = document.createElement('button');
    const stopButton = document.createElement('button');

    strtButton.textContent = 'Start Recording';
    stopButton.textContent = 'Stop Recording';
    
    document.body.appendChild(div);
    div.appendChild(strtButton);
    div.appendChild(audio);

    const stream = await navigator.mediaDevices.getUserMedia({audio:true});
    let recorder = new MediaRecorder(stream);
    
    audio.style.display = 'block';
    audio.srcObject = stream;
    audio.controls = true;
    audio.muted = true;

    await new Promise((resolve) => strtButton.onclick = resolve);
      strtButton.replaceWith(stopButton);
      recorder.start();

    await new Promise((resolve) => stopButton.onclick = resolve);
      recorder.stop();
      let recData = await new Promise((resolve) => recorder.ondataavailable = resolve);
      let arrBuff = await recData.data.arrayBuffer();
      stream.getAudioTracks()[0].stop();
      div.remove()

      let binaryString = '';
      let bytes = new Uint8Array(arrBuff);
      bytes.forEach((byte) => { binaryString += String.fromCharCode(byte) });

    const url = URL.createObjectURL(recData.data);
    const player = document.createElement('audio');
    player.controls = true;
    player.src = url;
    document.body.appendChild(player);

  return btoa(binaryString)};

""")

# Record audio
display(js)
output = eval_js('recordAudio({})')
with open('audio.wav','wb') as file:
  binary = base64.b64decode(output)
  file.write(binary)
print('Recording saved to:', file.name)
