# -*- coding: utf-8 -*-
"""#16 Using camera

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fZSw50x4tWMhwv1eDT2-BDm-dpTiYgx?usp=sharing

# **Using camera in Colab**

"""

from IPython.display import HTML, Javascript
from google.colab.output import eval_js
import base64

# Code a Java script
js = Javascript("""

  async function recordVideo() {

    const div = document.createElement('div');
    const video = document.createElement('video');
    const strtButton = document.createElement('button');
    const stopButton = document.createElement('button');

    strtButton.textContent = 'Start Recording';
    stopButton.textContent = 'Stop Recording';
    
    document.body.appendChild(div);
    div.appendChild(strtButton);
    div.appendChild(video);

    const stream = await navigator.mediaDevices.getUserMedia({ audio:true, video:true });
    let recorder = new MediaRecorder(stream);

    video.style.display = 'block';
    video.srcObject = stream;
    video.muted = true;
    await video.play();

    await new Promise((resolve) => strtButton.onclick = resolve);
      strtButton.replaceWith(stopButton);
      recorder.start();

    await new Promise((resolve) => stopButton.onclick = resolve);
      recorder.stop();
      let recData = await new Promise((resolve) => recorder.ondataavailable = resolve);
      let arrBuff = await recData.data.arrayBuffer();
      stream.getVideoTracks()[0].stop();
      div.remove()

      let binaryString = '';
      let bytes = new Uint8Array(arrBuff);
      bytes.forEach((byte) => { binaryString += String.fromCharCode(byte) });
    
    const url = URL.createObjectURL(recData.data);
    const player = document.createElement('video');
    player.controls = true;
    player.src = url;
    document.body.appendChild(player);

  return btoa(binaryString)};

""")

# Record video
display(js)
output = eval_js('recordVideo({})')
with open('video.mp4','wb') as file:
  binary = base64.b64decode(output)
  file.write(binary)
print('Recording saved to:', file.name)
