# -*- coding: utf-8 -*-
"""#13 Highlight names in text

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qo7Ut0-OZMoFqqITandDhTVJBafSH4y-?usp=sharing

# **Highlight names in text**


"""

pip install polyglot pyicu pycld2 morfessor colorama

from IPython.display import HTML, display
from polyglot.text import Text
from colorama import Back

# Set up a text wrap
def set_css():
  display(HTML('''<style>pre {white-space: pre-wrap;}</style>'''))
get_ipython().events.register('pre_run_cell', set_css)

# Load text
file = open('/content/The Surprising History of the Pencil.txt', 'r')
text = file.read()
print(text)

# Download NER vocabulary for English
%%bash
polyglot download ner2.en embeddings2.en

# Highlight names
names = Text(text).entities
for n in names:
  if n.tag == 'I-PER':
    text = text.replace(n[0], Back.LIGHTCYAN_EX + n[0] + Back.RESET)
  elif n.tag == 'I-ORG':
    text = text.replace(n[0], Back.LIGHTMAGENTA_EX + n[0] + Back.RESET)
  elif n.tag == 'I-LOC':
    text = text.replace(n[0], Back.LIGHTYELLOW_EX + n[0] + Back.RESET)
text = text.replace('pencil', Back.LIGHTBLUE_EX + 'pencil' + Back.RESET)
print(text)
