# -*- coding: utf-8 -*-
"""#14 Say Ah with Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OA5LLmsekuaRWd43ff8CSBDlM_2kl_Xo?usp=sharing

# **Say "Ah" and "Oh" with Python**

"""

import matplotlib.pyplot as plt
import IPython.display as ipd
import numpy as np
import librosa

"""**Building "Aah"**"""

# Read "Aah"
audio, srate = librosa.load('/content/aaahoooh.m4a')
voice = audio[25000:35000]
ipd.Audio(data=voice, rate=srate)

# Build artificial "Aah"
t = np.int16([i for i in range(10000)])
spec = np.fft.rfft(voice)
freq = np.where(spec>5)[0]
spec[spec<5] = 0

Amp = np.zeros(10000)
for f in freq:
  Amp = Amp + (2/10000 * (spec[f].real * np.cos(f * 2 * np.pi * t/10000) - 
                          spec[f].imag * np.sin(f * 2 * np.pi * t/10000)))

plt.figure(figsize=(25,5))
plt.subplot(121); plt.plot(abs(spec[:500]))
plt.subplot(122); plt.plot(Amp[1000:2000])
plt.show()

ipd.Audio(data=Amp, rate=srate)

"""**Building "Ooh"**"""

# Read "Ooh"
audio, srate = librosa.load('/content/aaahoooh.m4a')
voice = audio[60000:70000]
ipd.Audio(data=voice, rate=srate)

# Build artificial "Ooh"
t = np.int16([i for i in range(10000)])
spec = np.fft.rfft(voice)
freq = np.where(spec>5)[0]
spec[spec<5] = 0

Amp = np.zeros(10000)
for f in freq:
  Amp = Amp + (2/10000 * (spec[f].real * np.cos(f * 2 * np.pi * t/10000) - 
                          spec[f].imag * np.sin(f * 2 * np.pi * t/10000)))

plt.figure(figsize=(25,5))
plt.subplot(121); plt.plot(abs(spec[:500]))
plt.subplot(122); plt.plot(Amp[1000:2000])
plt.show()

ipd.Audio(data=Amp, rate=srate)
