# -*- coding: utf-8 -*-
"""#15 Find in video

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o-b7YboaVMXehL7a8TeYmcBuK9Qf4_qU?usp=sharing

# **Find in video**

"""

pip install ffmpeg

from IPython.display import HTML
import matplotlib.pyplot as plt
import ffmpeg, base64
from glob import glob
from PIL import Image
import numpy as np
import cv2

# Play video
video = open('elephant.mp4', 'rb').read()
url = 'data: ; base64,' + base64.b64encode(video).decode()
HTML('''<video controls style="height: 340px;">
          <source src= "%s" type="video/mp4"/>
        </video>''' % url)

# Load the image
img = np.array(Image.open('/content/ball.png').convert('RGB'))
plt.imshow(img)

# Split video into frames
!ffmpeg -i elephant.mp4 /content/frames/%04d.png

# Find the image in video
fps = 30
for file in sorted(glob('/content/frames/*.png')):
  frame = np.array(Image.open(file).convert('RGB'))
  
  heat_map = cv2.matchTemplate(frame, img, cv2.TM_CCOEFF_NORMED)
  if heat_map.max() > 0.9:
    frame_no = int(file[-8:-4])
    print('Frame:', frame_no, ', time:', round(frame_no/fps, 1), 'sec')
    y, x = np.unravel_index(np.argmax(heat_map), heat_map.shape)
    cv2.rectangle(frame, (x,y), (x+60, y+60), (255,0,0,255), 2)
    plt.imshow(frame)
    break
